namespace InteractiveBrokers.Models
{
	public enum MarginLevelCd
	{
		UNSPECIFIED, MARGIN_TRADING_NOT_ALLOWED, MARGIN_TRADING_ALLOWED, MARGIN_TRADING_ALLOWED_ON_OPTIONS, MARGIN_TRADING_ALLOWED_ON_PM
	}
}
