namespace InteractiveBrokers.Models
{
	public enum OrderType
	{
		EQ, OPTN, SPREADS, BUY_WRITES, BUTTERFLY, IRON_BUTTERFLY, CONDOR, IRON_CONDOR, MF, MMF, BOND, CONTINGENT, ONE_CANCELS_ALL, ONE_TRIGGERS_ALL, ONE_TRIGGERS_OCO, OPTION_EXERCISE, OPTION_ASSIGNMENT, OPTION_EXPIRED, DO_NOT_EXERCISE, BRACKETED
	}
}
